# Generated by Django 3.0.2 on 2020-01-15 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alerts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('title', models.CharField(max_length=255)),
                ('severity', models.CharField(max_length=100)),
                ('time', models.DateTimeField()),
                ('expires', models.DateTimeField()),
                ('description', models.TextField()),
                ('uri', models.URLField()),
            ],
            options={
                'unique_together': {('latitude', 'longitude', 'time', 'expires')},
            },
        ),
        migrations.CreateModel(
            name='AlertRegions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=255)),
                ('time', models.DateTimeField()),
                ('expires', models.DateTimeField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_data.Alerts')),
            ],
            options={
                'unique_together': {('latitude', 'longitude', 'time', 'expires')},
            },
        ),
    ]
