# Generated by Django 3.0.2 on 2020-02-04 20:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlertRegions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecastID', models.UUIDField(auto_created=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('geohash', models.CharField(max_length=12, null=True)),
                ('time', models.DateTimeField()),
                ('region', models.CharField(max_length=255)),
                ('expires', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'AlertRegions',
            },
        ),
        migrations.CreateModel(
            name='Alerts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecastID', models.UUIDField(auto_created=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('geohash', models.CharField(max_length=12, null=True)),
                ('time', models.DateTimeField()),
                ('title', models.CharField(max_length=255)),
                ('severity', models.CharField(max_length=100)),
                ('expires', models.DateTimeField()),
                ('description', models.TextField()),
                ('uri', models.URLField()),
            ],
            options={
                'verbose_name_plural': 'Alerts',
            },
        ),
        migrations.CreateModel(
            name='DailyInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecastID', models.UUIDField(auto_created=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('geohash', models.CharField(max_length=12, null=True)),
                ('time', models.DateTimeField()),
                ('precipType', models.CharField(max_length=100)),
                ('summary', models.CharField(max_length=255)),
                ('icon', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'DailyInfo',
            },
        ),
        migrations.CreateModel(
            name='DailyStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecastID', models.UUIDField(auto_created=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('geohash', models.CharField(max_length=12, null=True)),
                ('time', models.DateTimeField()),
                ('cloudCover', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('dewPoint', models.FloatField(default=0)),
                ('humidity', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('ozone', models.FloatField()),
                ('precipAccumulation', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('precipIntensity', models.FloatField()),
                ('precipProbability', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('pressure', models.FloatField()),
                ('uvIndex', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('visibility', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('windBearing', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(360)])),
                ('windGust', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('windSpeed', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('apparentTemperatureHigh', models.FloatField()),
                ('apparentTemperatureHighTime', models.DateTimeField()),
                ('apparentTemperatureLow', models.FloatField()),
                ('apparentTemperatureLowTime', models.DateTimeField()),
                ('apparentTemperatureMax', models.FloatField()),
                ('apparentTemperatureMaxTime', models.DateTimeField()),
                ('apparentTemperatureMin', models.FloatField()),
                ('apparentTemperatureMinTime', models.DateTimeField()),
                ('moonPhase', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('precipIntensityMax', models.FloatField()),
                ('precipIntensityMaxTime', models.DateTimeField()),
                ('sunriseTime', models.DateTimeField()),
                ('sunsetTime', models.DateTimeField()),
                ('temperatureHigh', models.FloatField()),
                ('temperatureHighTime', models.DateTimeField()),
                ('temperatureLow', models.FloatField()),
                ('temperatureLowTime', models.DateTimeField()),
                ('temperatureMax', models.FloatField()),
                ('temperatureMaxTime', models.DateTimeField()),
                ('temperatureMin', models.FloatField()),
                ('temperatureMinTime', models.DateTimeField()),
                ('windGustTime', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'DailyStats',
            },
        ),
        migrations.CreateModel(
            name='HourlyInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecastID', models.UUIDField(auto_created=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('geohash', models.CharField(max_length=12, null=True)),
                ('time', models.DateTimeField()),
                ('precipType', models.CharField(max_length=100)),
                ('summary', models.CharField(max_length=255)),
                ('icon', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'HourlyInfo',
            },
        ),
        migrations.CreateModel(
            name='HourlyStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecastID', models.UUIDField(auto_created=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('geohash', models.CharField(max_length=12, null=True)),
                ('time', models.DateTimeField()),
                ('cloudCover', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('dewPoint', models.FloatField(default=0)),
                ('humidity', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('ozone', models.FloatField()),
                ('precipAccumulation', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('precipIntensity', models.FloatField()),
                ('precipProbability', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('pressure', models.FloatField()),
                ('uvIndex', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('visibility', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('windBearing', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(360)])),
                ('windGust', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('windSpeed', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('apparentTemperature', models.FloatField()),
                ('temperature', models.FloatField()),
            ],
            options={
                'verbose_name_plural': 'HourlyStats',
            },
        ),
        migrations.AddConstraint(
            model_name='hourlystats',
            constraint=models.UniqueConstraint(fields=('geohash', 'time'), name='hourly_stats_unique_together'),
        ),
        migrations.AddConstraint(
            model_name='hourlyinfo',
            constraint=models.UniqueConstraint(fields=('geohash', 'time'), name='hourly_info_unique_together'),
        ),
        migrations.AddConstraint(
            model_name='dailystats',
            constraint=models.UniqueConstraint(fields=('geohash', 'time'), name='daily_stats_unique_together'),
        ),
        migrations.AddConstraint(
            model_name='dailyinfo',
            constraint=models.UniqueConstraint(fields=('geohash', 'time'), name='daily_info_unique_together'),
        ),
        migrations.AddConstraint(
            model_name='alerts',
            constraint=models.UniqueConstraint(fields=('geohash', 'time', 'expires'), name='alerts_unique_together'),
        ),
        migrations.AddConstraint(
            model_name='alertregions',
            constraint=models.UniqueConstraint(fields=('geohash', 'time', 'expires'), name='regions_unique_together'),
        ),
    ]
