# Generated by Django 3.0.2 on 2020-02-11 20:01

import api_data.custom_fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MappingData',
            fields=[
                ('ID', models.AutoField(db_column='id', editable=False, primary_key=True, serialize=False)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('city', models.CharField(max_length=100)),
                ('state_id', models.CharField(max_length=2)),
                ('state_name', models.CharField(max_length=100)),
                ('county_fips', models.IntegerField()),
                ('county_name', models.CharField(max_length=100)),
                ('county_fips_all', api_data.custom_fields.SeparatedValuesField()),
                ('county_name_all', api_data.custom_fields.SeparatedValuesField()),
                ('population', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('density', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('incorporated', models.BooleanField()),
                ('timezone', models.CharField(max_length=100)),
                ('ranking', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
                ('zips', api_data.custom_fields.SeparatedValuesField()),
            ],
        ),
    ]
